version: '2.4'

services:
  manager:
    build:
      context: ./manager
    restart: "unless-stopped"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/web_njs/:/tmp/web_njs/
    ports:
      - 80:80
    cap_drop:
      - all
    cap_add:
      - SETGID  # su
      - SETUID  # su
      - AUDIT_WRITE  # su
      - NET_BIND_SERVICE  # nginx / bind
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"

  # only for build image ;)
  sandboxtask:
    build:
      context: ./sandboxtask
    image: sandboxtask
    restart: "no"
    command: /bin/bash -c 'echo 1;'
