version: '3'

services:
  bot:
    build: .
    restart: unless-stopped
    ports:
      - 80:8080
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE  # bind
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
