version: '2.4'

services:
  webgofs:
    build:
      context: ./private/
    restart: "unless-stopped"
    ports:
      - 80:80
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
